/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import { Float, MeshReflectorMaterial, useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { Annotation } from './Annotation'

export function Escaparate({ reflectionResolution = 512, onSelect, hideAnnotations = false, ...props }) {
  const { nodes } = useGLTF('/escaparate_modelo.glb')
  const alphaMap = useTexture('/alpha.png')
  alphaMap.colorSpace = THREE.NoColorSpace
  alphaMap.flipY = false
  alphaMap.wrapS = THREE.ClampToEdgeWrapping
  alphaMap.wrapT = THREE.ClampToEdgeWrapping
  alphaMap.needsUpdate = true
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PAREDES.geometry}
        material={nodes.PAREDES.material}
        position={[0, 0.152, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PISO.geometry}
        material={nodes.PISO.material}
        position={[0, 0.152, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.STAGE.geometry}
        material={nodes.STAGE.material}
        position={[0, 0.152, 0]}
      />
      <group position={[-2.1, 1.362, -0.56]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CUBO.geometry}
          material={nodes.CUBO.material}
          position={[-0.094, 0.646, -0.01]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LETRERO.geometry}
          material={nodes.LETRERO.material}
          position={[-0.094, 0.646, -0.01]}
          rotation={[0, 1.571, 0]}
          scale={[1, -1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IMAGEN.geometry}
          material={nodes.IMAGEN.material}
          material-transparent
          material-alphaMap={alphaMap}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh castShadow receiveShadow geometry={nodes.MARCO.geometry} material={nodes.MARCO.material} />
      </group>
      <group position={[-2.1, 1.362, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CUBO_1.geometry}
          material={nodes.CUBO_1.material}
          position={[-0.094, 0.646, 0.005]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LETRERO_1.geometry}
          material={nodes.LETRERO_1.material}
          position={[-0.094, 0.646, 0.005]}
          rotation={[0, 1.571, 0]}
          scale={[1, -1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IMAGEN_1.geometry}
          material={nodes.IMAGEN_1.material}
          material-transparent
          material-alphaMap={alphaMap}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <Annotation
          label="Poster"
          author="Diego Herrera"
          title="Poster"
          detail="Pieza gráfica del escaparate. Una abstraccion geometrica de un pato."
          image="/detalles/imagen.png"
          position={[0.1, 0.55, 0.8]}
          onSelect={onSelect}
          hidden={hideAnnotations}
        />
        <mesh castShadow receiveShadow geometry={nodes.MARCO_1.geometry} material={nodes.MARCO_1.material} />
      </group>
      <group position={[0.136, 1.309, -1.639]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VIDRIO.geometry}
          position={[-0.001, -0.001, -0.05]}
        >
          <MeshReflectorMaterial
            blur={[0, 0]}
            mixBlur={0}
            mixStrength={2.8}
            mixContrast={1}
            resolution={reflectionResolution}
            mirror={1}
            depthScale={0}
            minDepthThreshold={0.9}
            maxDepthThreshold={1}
            depthToBlurRatioBias={0.25}
            distortion={0}
            reflectorOffset={0.2}
            roughness={0.4}
            metalness={0.8}
            color="#ffffff"
          />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.MARCO_2.geometry} material={nodes.MARCO_2.material} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MUEBLE_1.geometry}
        material={nodes.MUEBLE_1.material}
        position={[1.858, 0.725, -0.903]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MUEBLE_2.geometry}
        material={nodes.MUEBLE_2.material}
        position={[1.858, 0.725, 1.364]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MUEBLE_3.geometry}
        material={nodes.MUEBLE_3.material}
        position={[-0.362, 0.725, 1.364]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TAPETE.geometry}
        material={nodes.TAPETE.material}
        position={[-0.488, 0.301, -0.495]}
      />
      <Float speed={1.2} rotationIntensity={0.12} floatIntensity={0.35} floatingRange={[-0.04, 0.04]}>
        <group position={[1.917, 1.332, -0.864]} rotation={[0.288, -0.987, 0.245]}>
          <group position={[0.006, 0.086, 0.002]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill.geometry}
              material={nodes.Fill.material}
              position={[0.218, 0.012, -0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_1.geometry}
              material={nodes.Fill_1.material}
              position={[-0.09, 0.012, -0.008]}
            />
          </group>
          <group position={[-0.043, 0.104, 0.004]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_2.geometry}
              material={nodes.Fill_2.material}
              position={[0, 0, -0.062]}
              rotation={[Math.PI / 4, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill1.geometry}
              material={nodes.Fill1.material}
              position={[0, 0, 0.062]}
              rotation={[-0.698, 0, 0]}
            />
          </group>
        </group>
      </Float>
      <Float speed={1.6} rotationIntensity={0.1} floatIntensity={0.4} floatingRange={[-0.05, 0.05]}>
        <group position={[1.756, 1.329, 1.35]} rotation={[-3.011, -0.921, -3.046]}>
          <group position={[0.006, 0.086, 0.002]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_3.geometry}
              material={nodes.Fill_3.material}
              position={[0.218, 0.012, -0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_4.geometry}
              material={nodes.Fill_4.material}
              position={[-0.09, 0.012, -0.008]}
            />
          </group>
          <group position={[-0.043, 0.104, 0.004]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_5.geometry}
              material={nodes.Fill_5.material}
              position={[0, 0, -0.062]}
              rotation={[Math.PI / 4, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill1_1.geometry}
              material={nodes.Fill1_1.material}
              position={[0, 0, 0.062]}
              rotation={[-0.698, 0, 0]}
            />
          </group>
          <Annotation
            label="Móvil"
            title="Móvil"
            author="Porfirio Díaz"
            detail="Producto en exhibición sobre el mueble. El móvil de madera hecho a partir de la abstraccion del poster."
            image="/detalles/modelo.jpg"
            position={[0, 0.28, 0]}
            onSelect={onSelect}
            hidden={hideAnnotations}
          />
        </group>
      </Float>
      <Float speed={1.35} rotationIntensity={0.14} floatIntensity={0.3} floatingRange={[-0.035, 0.035]}>
        <group position={[-0.386, 1.324, 1.276]} rotation={[-0.176, -0.075, 0.155]}>
          <group position={[0.006, 0.086, 0.002]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_6.geometry}
              material={nodes.Fill_6.material}
              position={[0.218, 0.012, -0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_7.geometry}
              material={nodes.Fill_7.material}
              position={[-0.09, 0.012, -0.008]}
            />
          </group>
          <group position={[-0.043, 0.104, 0.004]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill_8.geometry}
              material={nodes.Fill_8.material}
              position={[0, 0, -0.062]}
              rotation={[Math.PI / 4, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fill1_2.geometry}
              material={nodes.Fill1_2.material}
              position={[0, 0, 0.062]}
              rotation={[-0.698, 0, 0]}
            />
          </group>
        </group>
      </Float>
    </group>
  )
}

useGLTF.preload('/escaparate_modelo.glb')
